### ISSUE TITLE
The desktop shortcut generated by win11 is blank

### ISSUE THREAD

**Issue by mmylll** [mjfusa/msix-create-desktop-shortcuts#1]
For the win11 operating system, the generated shortcut seems to have an incorrect icon path, so it is blank. It should be impossible to copy the icon in msix to the specified path. But after modifying the copy path, it can be achieved again.

**Comment by mmylll** [comment]
It should be possible to further automate and automatically modify msix, which is more convenient to use.

**Comment by mjfusa** [comment]
I'm glad you go this work. Thanks for the comment. This works on Windows 11.
